package exceptiondemo;

import java.util.Scanner;

/**
 * Author :Jetty.Srikar
 * Date :Sep 6, 2025
 * Time :2:23:21â€¯PM
 *project : projCoreJava
 */

public class DivisionDemo {

	public static void main(String[] args) {
		//Program to find Division of 2 nos without Exception Handling

		int a, b, result;
		Scanner input = new Scanner(System.in);

		System.out.println("Input two integers :");
		a = input.nextInt();
		b = input.nextInt();
		try {
			result = a / b;
			System.out.println("Result = " + result);

		}
		catch (ArithmeticException e) {
			System.err.println("Exception Caught: Division by Zero");
		}

		finally {
			input.close();
			System.out.println("Inside Finally Block");	
		}
	}
}
